<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.3.5 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Wed, 20 Feb 2013 04:47:08 +0800
 */

/* Servers configuration */
$i = 0;

/* Server: TeamAwesomeSauce [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'TeamAwesomeSauce';
$cfg['Servers'][$i]['host'] = 'goldberglinux02.tamu.edu';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'admin';

/* End of servers configuration */

$cfg['blowfish_secret'] = '5123e3b252e319.03193396';
$cfg['DefaultLang'] = 'en-utf-8';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['BZipDump'] = false;
?>